// <auto-generated />
using System;
using ASTROBIT_BACKEND;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ASTROBIT_BACKEND.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20220520210312_TipoPerfil")]
    partial class TipoPerfil
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("ASTROBIT_BACKEND.Entidades.Moeda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .HasColumnType("text");

                    b.Property<string>("Valor")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Moeda");
                });

            modelBuilder.Entity("ASTROBIT_BACKEND.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("Senha")
                        .HasColumnType("text");

                    b.Property<string>("TipoPerfil")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("USUARIO");
                });

            modelBuilder.Entity("ASTROBIT_BACKEND.Entidades.UsuarioMoeda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("MoedaId")
                        .HasColumnType("text");

                    b.Property<int?>("MoedaId1")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MoedaId1");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioMoeda");
                });

            modelBuilder.Entity("ASTROBIT_BACKEND.Entidades.UsuarioMoeda", b =>
                {
                    b.HasOne("ASTROBIT_BACKEND.Entidades.Moeda", "Moeda")
                        .WithMany()
                        .HasForeignKey("MoedaId1");

                    b.HasOne("ASTROBIT_BACKEND.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Moeda");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
